CC=g++
CPPFLAGS=-std=c++98 -Wall
LFLAGS=-lcurses
NAME=aburatan

all: aburatan

aburatan: src/action.cpp src/action.hpp src/actor.cpp src/actor.hpp src/ammo.cpp src/ammo.hpp src/attack.cpp src/attack.hpp src/bagbox.cpp src/bagbox.hpp src/book.cpp src/book.hpp src/catalog.cpp src/catalog.hpp src/clothing.cpp src/clothing.hpp src/cloud.cpp src/cloud.hpp src/compiler.cpp src/compiler.hpp src/config.hpp src/counted.cpp src/counted.hpp src/creature.cpp src/creature.hpp src/crlist.cpp src/crlist.hpp src/define.hpp src/dialog.cpp src/dialog.hpp src/diceroll.cpp src/diceroll.hpp src/dir.cpp src/dir.hpp src/door.cpp src/door.hpp src/dun_test.cpp src/dun_test.hpp src/enum.cpp src/enum.hpp src/error.cpp src/error.hpp src/event.cpp src/event.hpp src/feature.cpp src/feature.hpp src/features.cpp src/features.hpp src/file.cpp src/file.hpp src/fluid.cpp src/fluid.hpp src/food.cpp src/food.hpp src/function.cpp src/function.hpp src/global.cpp src/global.hpp src/grammar.cpp src/grammar.hpp src/input.cpp src/input.hpp src/item.cpp src/item.hpp src/itemlist.cpp src/itemlist.hpp src/level.cpp src/level.hpp src/list.cpp src/list.hpp src/main.cpp src/main.hpp src/map.cpp src/map.hpp src/menu.cpp src/menu.hpp src/message.cpp src/message.hpp src/misc.cpp src/misc.hpp src/money.cpp src/money.hpp src/monster.cpp src/monster.hpp src/mtint.hpp src/name.cpp src/name.hpp src/path.cpp src/path.hpp src/player.cpp src/player.hpp src/playerui.cpp src/playerui.hpp src/point.cpp src/point.hpp src/quantity.cpp src/quantity.hpp src/quest.cpp src/quest.hpp src/random.cpp src/random.hpp src/rawtargt.cpp src/rawtargt.hpp src/rectngle.cpp src/rectngle.hpp src/resource.cpp src/resource.hpp src/scope.cpp src/scope.hpp src/serial.cpp src/serial.hpp src/skill.cpp src/skill.hpp src/sorted.cpp src/sorted.hpp src/stairs.cpp src/stairs.hpp src/standard.cpp src/standard.hpp src/stats.cpp src/stats.hpp src/string.cpp src/string.hpp src/target.cpp src/target.hpp src/temp.cpp src/temp.hpp src/terrain.cpp src/terrain.hpp src/tile.cpp src/tile.hpp src/timeline.cpp src/timeline.hpp src/trap.cpp src/trap.hpp src/types.hpp src/unique.cpp src/unique.hpp src/viewable.cpp src/viewable.hpp src/visuals.cpp src/visuals.hpp src/weapon.cpp src/weapon.hpp src/widget.cpp src/widget.hpp
	$(CC) $(CPPFLAGS) $(LFLAGS) -o $(NAME) src/main.cpp

src/%: src/%
